config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "foods#index"

  # resources :foods, only: %i[index show]
 
  resources :users, only: %i[index show] do 
    resources :foods
    resources :inventories
    resources :shopping_list
    resources :recipe_foods
    resources :recipes do
      resources :recipe_foods
    end

   
    resources :shopping_list, only: %i[index show]
    resources :inventories do
      resources :inventory_foods, only: %i[new create destroy]
    end

  end
  
  get 'public_recipes', to: 'recipes#public_recipes'
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user
  has_many :inventory_foods, dependent: :destroy
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  load_and_authorize_resource

  def index
    @inventories = current_user.inventories
  end

  def new
    @inventory = Inventory.new
  end

  def create
    @inventory = Inventory.new(inventory_params)
    @inventory.user = current_user

    if @inventory.save
      redirect_to user_inventories_path, notice: 'Inventory added succesfully'
    else
      render :new
    end
  end

  def show
    @inventory = Inventory.find(params[:id])
    @inventory_foods = @inventory.inventory_foods
    @arr = @inventory_foods.map(&:food_id)
    @foods = current_user.foods.joins(:inventory_foods).where(id: @arr).uniq
  end

  def destroy
    @inventory = Inventory.find(params[:id])
    @inventory.destroy

    redirect_to user_inventories_path, alert: 'Inventory deleted succesfully'
  end

  private

  def inventory_params
    params.require(:inventory).permit(:name, :description)
  end
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/views/inventories/index.html.erb
<div class="container d-flex flex-column p-4">
<%= link_to 'Create new inventory', new_user_inventory_path(params[:user_id]), class:'btn btn-success btn-sm align-self-end' %>
<ul class="d-flex flex-column">
  <% @inventories.each do |inventory| %>
   <li class="d-flex  border border-muted mt-2 mb-2 p-3 rounded">
   
    <div class="d-flex flex-column align-items-center mr-2 w-25">
     <%= link_to user_inventory_path(inventory.user.id, inventory.id), class:"text-primary" do %>
      <h2 ><%= inventory.name%></h2>
     <% end %>

      <% if can? :destroy, inventory %>
        <%= button_to 'Remove', { :controller => :inventories, :action => :destroy, :id=> inventory.id }, method: :delete, class:'btn btn-outline-danger btn-sm mt-2' %>
      <% end %>

    </div>
      <p class="align-self-start p-3 w-75"><%= inventory.description %><h2>
   </li> 
   <% end %>
  </ul>
<div>

app/views/inventories/new.html.erb
<div class='container d-flex justify-content-center p-3'>
<%= form_with model: Inventory.new, :url => {:action => :create, :controller => :inventories}, class: 'form-group w-50 d-flex flex-column' do |form| %>
  <h1 class="text-secondary align-center mb-3">New inventory</h1>
  <div>
    <%= form.label :name%>
    <%= form.text_field :name, class: 'form-control mb-3 mt-3', placeholder:'Inventory name' %>
    
  </div>
  <div>
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control mt-3 mb-3', placeholder:'Inventory description' %>
  </div>

  <%= form.submit "Create inventory", class:"btn btn-primary align-self-end mt-4 pe-3 ps-3" %>
  <% end %>
</div>

app/views/inventories/show.html.erb
<div class='container d-flex flex-column p-5'>
  <h2 class="align-self-center"><%= @inventory.name %></h2>
  <%= link_to 'Add food', new_user_inventory_inventory_food_path(params[:user_id], params[:id]), class:'btn btn-success btn-sm align-self-end' %>
  <hr>

  <% if @foods.size >0 %>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Food</th>
            <th scope="col">Quantity</th>
            <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @foods.each do |food| %>
        <% inventory_food = @inventory_foods.select {|inv| inv.food_id==food.id} %>
        <tr>
          <td><%= food.name%></td>
          <td><%= inventory_food[0].quantity %> <%= food.measurement_unit %></td>
          <td>
            <% if can? :destroy, InventoryFood %>
              <%= button_to 'Remove', user_inventory_path(params[:user_id], params[:id])+'/inventory_foods/'+inventory_food[0].id.to_s, method: :delete, class:'btn btn-danger btn-sm' %>
              <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>