config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "foods#index"

  # resources :foods, only: %i[index show]
 
  resources :users, only: %i[index show] do 
    resources :foods
    resources :inventories
    resources :shopping_list
    resources :recipe_foods
    resources :recipes do
      resources :recipe_foods
    end

   
    resources :shopping_list, only: %i[index show]
    resources :inventories do
      resources :inventory_foods, only: %i[new create destroy]
    end

  end
  
  get 'public_recipes', to: 'recipes#public_recipes'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user

  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods

  validates :name, :preparation_time, :cooking_time, :description, presence: true

  def total_price
    foods.sum(&:price)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  load_and_authorize_resource
  def index
    @recipes = current_user.recipes
  end

  def new
    @recipe = Recipe.new
  end

  def show
    @recipe = Recipe.where(id: params[:id]).includes(:recipe_foods).take
    @recipe_foods = @recipe.recipe_foods
    @inventories = current_user.inventories.all
  end

  def update
    @recipe = Recipe.find(params[:id])
    @recipe.update(params.require(:recipe).permit(:public))
  end

  def public_recipes
    @recipes = Recipe.where({ public: true }).order(created_at: :desc).includes(:user)
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)
    flash[:notice] = 'Recipe is Created!' if @recipe.save
    redirect_to user_recipes_path
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    authorize! :destroy, @recipe
    @recipe.destroy
    flash[:notice] = 'Recipe has been destroyed!'
    redirect_to user_recipes_path
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<% if recipe.errors.present? %>
  <div class="errors notification is-danger is-light">
    <h3 class="title is-5"><%= pluralize(recipe.errors.count, "error") %> Cannot save this recipe:</h3>
    <ul>
      <% recipe.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_with url: user_recipes_path, model: @recipe do |form| %>
  <div class="mb-3">
    <%= form.label :name, { class: "form-label"} %>
    <%= form.text_field :name, { class: "form-control", required: true, placeholder: "Please enter recipe name", value: nil } %>
  </div>

  <div class="mb-3">
    <%= form.label :preparation_time, { class: "form-label"} %>
    <%= form.text_field :preparation_time, { class: "form-control", required: true, placeholder: "How long is the preparation?", value: nil } %>
  </div>

  <div class="mb-3">
    <%= form.label :cooking_time, { class: "form-label"} %>
    <%= form.text_field :cooking_time, { class: "form-control", required: true, placeholder: "How long is the cooking?" } %>
  </div>

  <div class="mb-3">
    <%= form.label :description, { class: "form-label"} %>
    <%= form.text_area :description, { class: "form-control", required: true, placeholder: "Describe the process please" } %>
  </div>

  <div>
    <%= form.check_box :public %>
    <%= form.label :public %>
  </div>

  <div>
    <%= form.submit "Create Recipe", class: "btn btn-primary mt-3" %>
  </div>
<% end %>

app/views/recipes/_public_btn.html.erb
<%= form_with model: @recipe, url: user_recipe_path(@recipe), method: :patch, local: true do |form| %>
 <div class="custom-control custom-switch">
 <%= form.check_box :public, class: "custom-control-input", id: "customSwitch1" %>
   <label class="custom-control-label" for="customSwitch1">Public</label>
 </div>
 <div class="actions btn btn-">
      <%= form.submit "Submit status" %>
 </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div class="border border-muted d-flex ml-5 p-2 rounded" >
  <div class="columns w-25 p-1">
    <h2 class="p-2">
      <%= link_to recipe.name, user_recipe_path(current_user, recipe), class: "text-primary" %>
    </h2>
    <% if can? :destroy, recipe %>
      
        <%= link_to "Remove", user_recipe_path(current_user, recipe), method: :delete, data: { confirm: "Do you really want to delete this recipe?" }, class: "btn btn-outline-danger btn-sm mt-2 text-decoration-none mx-2" %>
    <% end %>
  </div>
  <div class="w-50 p-4">
    <p class="w-100 "><%= recipe.description %></p>
  </div>
</div>
<br/>

app/views/recipes/index.html.erb
<section class="flex-column d-flex  w-75 m-auto mt-3">
<div class="align-self-end mx-5 my-3"><%= link_to 'Create a new Recipe', new_user_recipe_path, class: "btn btn-primary btn-sm btn-block my-1" %></div>
<div class="container h-100">

  <div class="columns is-flex-direction-column is-align-items-center">
    <% @recipes.each do |recipe| %>
      <%= render partial: 'recipe', object: recipe %>
    <% end %>
  </div>
</div>
</section>

app/views/recipes/new.html.erb
<div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card shadow-2-strong" style="border-radius: 1rem;">
           <div class="card-body p-5">
              <h3 class="title text-center">New Recipe</h3>

                 <%= render 'form', recipe: @recipe %>
            </div>
        </div>
       </div>
    </div>
    <%= link_to 'Back to Create New Recipe', user_recipes_path, class: "btn btn-primary btn-sm btn-block ml-4" %>
</div>

app/views/recipes/public_recipes.html.erb
<div class="container border mt-4">
  <h2 class="title has-text-centered my-4">
   Public Recipes
  </h2>
  <% @recipes.each do |recipe| %>
    <div class="row justify-content-md-center my-4">
      <div class="row w-50">
        <div class="col-md-6 p-2">
          <h2><%= link_to recipe.name, user_recipe_path(current_user, recipe), class: "text-decoration-none" %></h2>
          <p>By: <%= recipe.user.name %></p>
        </div>
        <div class="col-md-6 p-2">
        <p>Total food items: <%= recipe.recipe_foods.size %></p>
        <p>Total price: <%= number_to_currency(recipe.total_price)%></p>
        </div>
    </div>
   </div>
    <% end %>
</div>

app/views/recipes/show.html.erb
<div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-10 col-lg-9 col-xl-8">
        <div class="card shadow-2-strong " style="border-radius: 1rem;">
          <div class="card-body p-2 text-center">
            <h1><%= @recipe.name %></h1>

            <div class="d-flex flex-column">

              <div class="row">
                <div class="col-md-6">
                  <p>Preparation time: <%= @recipe.preparation_time %></p>
                  <p>Cooking time: <%= @recipe.cooking_time %></p>
                  <div><%= @recipe.description %></div>
                </div>

                <div class="col-md-6">
                  <% if can? :update, @recipe %>
                    <%= render "public_btn" %>
                  <% end %>
                </div>
              </div>
              <div class="row">
                <div class="col-md-6 my-5">
                  <button type="button" class="btn btn-primary btn-lg" id="shop">Generate Shopping list</button>
                </div>
                <div class="col-md-6 my-5">
                  <% if can? :update, @recipe %> 
                    <%= link_to "Add Food", new_user_recipe_recipe_food_path(current_user, @recipe), class: "btn btn-primary btn-lg"%>
                  <% end %>
                </div>
              </div>     
              <div class="border-top border-secondary">
              </div>
              <br/>
              <table class="table table-striped table-hover table-bordered align-middle table-sm my-5">     
              <thead class="table-dark">

                  <th scope="col">Foods</th>
                  <th scope="col">Quantity</th>
                  <th scope="col">Value</th>
                  <th scope="col">Actions</th>
                  </tr>
              </thead>
              <tbody>

                <% @recipe_foods.each do |recipe_food| %>
                  <tr>
                    <td><%= recipe_food.food.name %></td>
                    <td><%= recipe_food.quantity %><%= recipe_food.food.measurement_unit %></td>
                    <td><%= number_to_currency((recipe_food.food.price).to_i * (recipe_food.quantity).to_i)%></td>
                    <td class="d-flex justify-content-center">
                        <%= button_to "Delete", user_recipe_recipe_food_path(current_user, @recipe, recipe_food), method: :delete, data: { confirm: 'Are you sure?' }, class: "r-food-btn btn btn-danger" %>
                        <%= link_to "Edit", edit_user_recipe_recipe_food_path(current_user, @recipe, recipe_food), class: "btn btn-primary mx-2 r-food-btn" %>
                    </td>
                  </tr>
                  <% end %>
              </tbody>
          </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- The Modal modal javascript is in app/asset/javascript/custom-->
<div id="myModal" class="modal">
  <!-- Modal content -->
  <div class="modal-content">
    <span class="close">&times;</span>
    <h4 class="text-center my-3">Generating Shopping list</h4>
      <h4>Select an inventory to use</h4>
             <%= form_with  url: user_shopping_list_index_path, method: :get do |form| %>
             <%= form.hidden_field :recipe_id, :value => params[:id] %>
             <div class="field">
            <div class="select-option">
              <%= form.select :inventory_id, @inventories.map { |t| [t.name, t.id]}, {}, class: 'form-control mb-3 mt-3', placeholder:'Inventory name' %>
            </div>
          </div>
        
        <div class="modal-footer">
          <%= form.submit "Generate", class: "btn btn-success mt-3" %>
      <% end %> 
  </div>
</div>