config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "foods#index"

  # resources :foods, only: %i[index show]
 
  resources :users, only: %i[index show] do 
    resources :foods
    resources :inventories
    resources :shopping_list
    resources :recipe_foods
    resources :recipes do
      resources :recipe_foods
    end

   
    resources :shopping_list, only: %i[index show]
    resources :inventories do
      resources :inventory_foods, only: %i[new create destroy]
    end

  end
  
  get 'public_recipes', to: 'recipes#public_recipes'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    user ||= User.new # guest user (not logged in)

    if user.role == 'admin'
      can :manage, :all
    else
      can :read, :all

      can :edit, Recipe, user: user
      can :update, Recipe, user: user
      can :manage, Recipe, user: user

      can :manage, Inventory, user_id: user.id
      can :manage, InventoryFood, user_id: user.id

      can :manage, Food, user: user
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :inventory_foods, dependent: :destroy
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user
  has_many :inventory_foods, dependent: :destroy
end

app/models/inventory_food.rb
class InventoryFood < ApplicationRecord
  belongs_to :food
  belongs_to :inventory

  validates :food_id, presence: true, uniqueness: { scope: :inventory_id }
  validates :quantity, presence: true, numericality: { greater_than: 0 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user

  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods

  validates :name, :preparation_time, :cooking_time, :description, presence: true

  def total_price
    foods.sum(&:price)
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :quantity, :food_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  after_create :set_default_role
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_many :foods, dependent: :destroy
  has_many :recipes, dependent: :destroy
  has_many :inventories, dependent: :destroy

  validates :name, presence: true

  private

  def set_default_role
    update(role: 'user')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password password_confirmation])
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @foods = current_user.foods.all
  end

  def show
    @food = Food.find(params[:id])
  end

  def new
    @food = current_user.foods.new
  end

  def create
    @food = current_user.foods.create(food_params)
    if @food.save
      redirect_to user_foods_path
    else
      render :new
    end
  end

  def destroy
    @food = current_user.foods.find(params[:id])
    @food.destroy
    redirect_to user_foods_path
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  load_and_authorize_resource
  def index
    @recipes = current_user.recipes
  end

  def new
    @recipe = Recipe.new
  end

  def show
    @recipe = Recipe.where(id: params[:id]).includes(:recipe_foods).take
    @recipe_foods = @recipe.recipe_foods
    @inventories = current_user.inventories.all
  end

  def update
    @recipe = Recipe.find(params[:id])
    @recipe.update(params.require(:recipe).permit(:public))
  end

  def public_recipes
    @recipes = Recipe.where({ public: true }).order(created_at: :desc).includes(:user)
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)
    flash[:notice] = 'Recipe is Created!' if @recipe.save
    redirect_to user_recipes_path
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    authorize! :destroy, @recipe
    @recipe.destroy
    flash[:notice] = 'Recipe has been destroyed!'
    redirect_to user_recipes_path
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/inventory_foods_helper.rb
module InventoryFoodsHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shopping_list_helper.rb
module ShoppingListHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">

  </head>
  <body>
  <%= render partial: "shared/navigation" %>
  <%= render partial: "shared/msg" %>
  <%= yield %>
  <div class="container"></div>
<%= javascript_pack_tag 'custom' %>
  </body>
</html>

app/views/shared/_msg.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/shared/_navigation.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "RecipeApp", root_path, class:'navbar navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <% if user_signed_in? %>
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to "Foods", user_foods_path(current_user), class:'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "Recipes", user_recipes_path(current_user), class:'nav-link' %>

            </li>
            <li class="nav-item">
              <%= link_to "Public recipes", public_recipes_path, class:'nav-link' %>

            </li>
            <li class="nav-item">
              <%= link_to "Inventories",user_inventories_path(current_user), class:'nav-link' %>

            </li>
          </ul>
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <li class="nav-item nav-link"><%= current_user.name%></li>
            <li class="nav-item">
            <%= link_to "Sign out", destroy_user_session_path, class:'nav-link', :method => :delete %>
            </li>
          </ul>
        <% else%>
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to "Sign In", new_user_session_path, class:'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign Up", new_user_registration_path, class:'nav-link' %>
            </li>
          </ul>
        <% end %>
    </div>
  </div>
</nav>