config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "foods#index"

  # resources :foods, only: %i[index show]
 
  resources :users, only: %i[index show] do 
    resources :foods
    resources :inventories
    resources :shopping_list
    resources :recipe_foods
    resources :recipes do
      resources :recipe_foods
    end

   
    resources :shopping_list, only: %i[index show]
    resources :inventories do
      resources :inventory_foods, only: %i[new create destroy]
    end

  end
  
  get 'public_recipes', to: 'recipes#public_recipes'
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :inventory_foods, dependent: :destroy
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @foods = current_user.foods.all
  end

  def show
    @food = Food.find(params[:id])
  end

  def new
    @food = current_user.foods.new
  end

  def create
    @food = current_user.foods.create(food_params)
    if @food.save
      redirect_to user_foods_path
    else
      render :new
    end
  end

  def destroy
    @food = current_user.foods.find(params[:id])
    @food.destroy
    redirect_to user_foods_path
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_table_row.html.erb
<tr>
    <td><%= food.name %></td>
    <td><%= food.measurement_unit %></td>
    <td><%= food.price %></td>
    <td class="d-flex justify-content-center">
        <%= button_to user_food_path(current_user, food), method: :delete, class: "btn btn-danger btn-sm m-1 ps-3 pe-3" do %>
            </span>Delete</span>
        <% end %>
    </td>
</tr>

app/views/foods/index.html.erb
<section class="foods d-flex mx-auto p-5 w-75 flex-column align-items-center">
    <div class=" align-self-end">
        <%= link_to new_user_food_path(@user.id) do%>
            <button class="btn btn-primary">Add Food</button>
        <% end %>
    </div>

    <table class="table table-striped table-hover table-bordered align-middle table-sm my-5">     
        <thead class="table-dark">

            <th scope="col">Foods</th>
            <th scope="col">Measurement unit</th>
            <th scope="col">Unit price</th>
            <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>

            <% @foods.each do |food| %>
                <%= render 'table_row', food: food %>
            <% end %>
        </tbody>
    </table>
</section>

app/views/foods/new.html.erb
<section class="new-food d-flex flex-column align-items-center justify-content-center ">
    <h2 class="text-secondary mt-4">Add New Food</h2>
 <%= form_with(model: @food, url: { action: "create" }) do |form| %>
    <div class="group-form">
        <%= form.label :name %><br />
        <%= form.text_field :name, autofocus: true, autocomplete: "name", class: "form-control"%>
    </div>

    <div class="group-form my-2">
        <%= form.label :"Measurement unit" %><br />
        <%= form.text_field :measurement_unit, autofocus: true, autocomplete: "measurement_unit", class: "form-control" %>
    </div>

    <div class="group-form">
        <%= form.label :"Price" %><br />
        <%= form.number_field :price, in: 1.0..20.0, step: 0.5, class: "form-control" %>
    </div>
  <%= form.submit "Add new food", class: "btn btn-primary my-3 align-self-end btn-submit" %>
  </div> 
   <% end %> 

</section>

app/views/foods/show.html.erb
<h1>Foods show page</h1>